### ISSUE TITLE
runlib: subprocess cleanup regularly fails on Windows

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#547]
*This issue was originally described in https://github.com/secure-systems-lab/securesystemslib/issues/337 (includes a bit of troubleshooting). In #544 the relevant code was moved to in-toto, making this an in-toto issue.*

----

**Description of issue or feature request**:

Windows regularly fails to remove a temporary file used in a subprocess. The file is created and opened (in a `with` block) in the parent process, and passed as file handle to a subprocess using the `Popen.stdout` argument. The file is removed (outside of the `with` block) in the parent process after the subprocess has exited.

* File is created and opened (twice, once for parent, once for subprocess):

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L342-L348

* File is passed to subprocess:

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L376-L378

* File is removed:

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L403

Error log from [failing ci run](https://github.com/in-toto/in-toto/actions/runs/4168226378/jobs/7214780020#step:7:809): 
```
======================================================================
ERROR: test_timeout_setting (tests.test_runlib.TestLinkCmdExecTimeoutSetting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 393, in _subprocess_run_duplicate_streams
    raise subprocess.TimeoutExpired(cmd, timeout)
subprocess.TimeoutExpired: Command '['D:\\a\\in-toto\\in-toto\\.tox\\py\\Scripts\\python.EXE', '-c', 'while True: pass']' timed out after 0.1 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\in-toto\in-toto\tests\test_runlib.py", line 515, in test_timeout_setting
    in_toto.runlib.execute_link([sys.executable, '-c', 'while True: pass'], True)
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 446, in execute_link
    _subprocess_run_duplicate_streams(
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 403, in _subprocess_run_duplicate_streams
    os.remove(stdout_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpd0h6tq_y'

```

**Comment by lukpueh** [comment]
This is really inconvenient. There's almost always at least one Windows run in our CI that fails, marking the whole build as failed each time. I'm inclined to just deactivate the  "record streams" feature on Windows, which is what we need this code branch for. Or, we indeed just record the streams on Windows but don't print them. 🤷

**Comment by lukpueh** [comment]
Using `with` to warp `Popen` does not fix this issue: https://github.com/in-toto/in-toto/pull/595

**Comment by lukpueh** [comment]
https://github.com/in-toto/in-toto/pull/597 provides a workaround.

**Comment by lukpueh** [comment]
Workaround seems to work. This a reference to this issue in the code comment, if we ever need to look at this again. Closing ...
